#!/bin/bash
FILE=~/.nvm
if test -d "$FILE"; then
    ./node-list;
    exit;
fi

wget -qO- https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash

. ~/.nvm/nvm.sh
. ~/.profile
. ~/.bashrc

nvm --version
nvm i v10
. ~/.nvm/nvm.sh
. ~/.profile
. ~/.bashrc


npm --version