#!/bin/bash

gsettings set org.gnome.shell favorite-apps "['google-chrome.desktop', 'org.gnome.Nautilus.desktop', 'org.gnome.Terminal.desktop']"
#gnome-tweaks;

arr=($accounts)
for account in "$arr" ;do
    echo "${account}"
    auth="${!account}"
   
    input="$(realpath ./configs/user/accounts/$(echo $account)/repos.txt)"
    
    cd ~/dev
    while IFS= read -r line
    do
        printf -v URL "$line" "$auth"
        git clone "$URL"
        echo "$URL"
    done <<< "$(tail $input)"    
done