#!/bin/bash
SCRIPT=`realpath $0`
SCRIPTPATH=`dirname $SCRIPT`

source ~/setup-ubuntu/lib/os

PROFILE="$1"
if [ "$PROFILE" == "" ]; then
PROFILE="desktop/default"
fi
echo " -> Setup $DISTRO:$VERSION_ID - $PROFILE";
echo " -----------------------------------------------------------";

FILE="$SCRIPTPATH/profiles/$PROFILE/install"
if ! test -f "$FILE"; then
    echo " -- PROFILE NOT FOUND                                     --";
    echo " -----------------------------------------------------------";
    exit;
fi

./profiles/$PROFILE/install
