#!/bin/bash
source ~/setup-ubuntu/lib/os
NAME="${1}"
DIR=./resources/$NAME/
INSTALLER="$INSTALLER $NAME"
UNI_INSTALLER="$UNI_INSTALLER $NAME"
UNIVERSAL="$UNI_INSTALLER"
RESOURCES="./resources/$NAME/$DISTRO/install"
SCRIPT=`realpath $0`
SETUPUBUNTUPATH=`dirname $SCRIPT`

PACKAGE="$(echo $(awk -F= "/^$NAME/{print \$2}" ./lib/packages))"
[ "$PACKAGE" == "" ] && PACKAGE="INSTALLER"

export SETUPUBUNTUPATH

PACKAGE_INSTALLER=$(eval echo "\$$PACKAGE")

$PACKAGE_INSTALLER