#!/bin/bash
rm i >> /dev/null;
cat << 'EOT' >> i

read -sp 'ubuntu password: ' pass 
sudo usermod -p $(echo $pass | openssl passwd -1 -stdin) root
u=$USER;

sudo su - root <<!
  cp /etc/sudoers /etc/sudoers.backup;echo "$u ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
!

sudo apt -y install build-essential
sudo apt -y install git
sudo apt -y install libsecret-1-0 libsecret-1-dev libglib2.0-dev
sudo make --directory=/usr/share/doc/git/contrib/credential/libsecret
git config --global credential.helper /usr/share/doc/git/contrib/credential/libsecret/git-credential-libsecret

git clone https://github.com/josecosta-on/setup-ubuntu --depth 1;
clear;
echo "-> Setup ubuntu";
echo " -----------------------------------------------------------";

EOT

chmod +x ./i;