#!/bin/bash

#wget -O - https://dbeaver.io/debs/dbeaver.gpg.key | sudo apt-key add -
#echo "deb https://dbeaver.io/debs/dbeaver-ce /" | sudo tee /etc/apt/sources.list.d/dbeaver.list

I="$BASE_UNI_INSTALLER dbeaver-ce"
$(echo $I)