#!/bin/bash

CHECK=$(php --version | awk '{print substr($0,1,4);exit}')

CHECK=$(echo $CHECK | tr "[:upper:]" "[:lower:]")
echo $CHECK

# PHPV="php7.1"
# PHPV="php7.2"
#PHPV="php7.3"
PHPV="php7.4"
# PHPV="php8.0"
IFS=$'\n';
for x in $(ls -1 -d /etc/apache2/mods-enabled/php*.conf) ;do
    FILE=${x//"/etc/apache2/mods-enabled/"/""}
    v=${FILE//".conf"/""}
    sudo a2dismod $v
done

sudo add-apt-repository -y ppa:ondrej/php
sudo apt -y install $PHPV
sudo apt-get -o Dpkg::Options::="--force-overwrite" install libpcre2-posix2
sudo update-alternatives --set php /usr/bin/$PHPV
sudo a2enmod $PHPV
sudo a2enmod proxy_fcgi setenvif
sudo a2enconf $PHPV-fpm

./lib/reader $0 php-default.txt "sudo apt install -y"
echo "######################### installing $PHPV ##############################"
./lib/reader $0 php.txt "./php $PHPV"
./lib/reader $0 php-base.txt "./php php"
sudo apt autoremove -y
sudo systemctl restart apache2
