#!/bin/bash
#gsettings list-recursively org.gnome.shell.extensions.$name

name="${1}"
echo "$name"


input="./resources/extensions/$name/settings.txt"
i=1;
while IFS= read -r line
do
  i=$(($i+1))
  if [ "$line" == "" ];
  then
    echo -e "\n"
  else
    gsettings set $line
    echo $i:: gsettings set $line
  fi
  
done < "$input"