#!/bin/bash
# gsettings list-recursively name 
# name like org.gnome.desktop.wm.keybindings

input="${1}"
echo "$input"

i=1;
while IFS= read -r line
do
   i=$(($i+1))
  if [ "$line" == "" ];
  then
   
    echo -e "\n"
  else
  
    gsettings set $line
    echo $i:: gsettings set $line
  fi
  
done < "$input"