#!/bin/bash
CHECK=$(gsettings get org.gnome.settings-daemon.plugins.media-keys custom-keybindings | awk '{print substr($0,3,74);exit}')

CHECK=$(echo $CHECK | tr "[:upper:]" "[:lower:]")
echo $CHECK

if [ "$CHECK" == "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/" ]; then

    gsettings set org.gnome.settings-daemon.plugins.media-keys terminal "['<Primary><Alt>t']"
    python3 ./lib/ubuntu/keyboard.py 'open nautilus' 'nautilus' '<Super>e'
    python3 ./lib/ubuntu/keyboard.py 'open sudo nautilus' 'sudo nautilus' '<Alt>e'


fi
   ./lib/ubuntu/set-apply keyboard