#!/bin/bash

SCRIPT=`realpath $0`
SCRIPTPATH=`dirname $SCRIPT`



I="$BASE_INSTALLER jq"
$(echo $I)

I="$INSTALLER"
$(echo $I)



FILE=~/.composer
if ! test -d "$FILE"; then
    mkdir ~/.composer    
    echo {} > ~/.composer/composer.json
fi
DEFAULT=$(cat ~/.composer/composer.json)
echo $DEFAULT
cat <<< $(jq ". *= $DEFAULT" "$SCRIPTPATH/../composer.json") > ~/.composer/composer.json

composer global update    



