#!/bin/bash

folder=~/DevTools

wget https://dl.google.com/android/repository/commandlinetools-linux-6609375_latest.zip

sudo mkdir $folder
sudo mkdir $folder/Android
sudo mkdir $folder/Android/cmdline-tools

unzip commandlinetools-linux-6609375_latest.zip

sudo mv tools $folder/Android/cmdline-tools/
sudo chmod 755 -R $folder/Android/cmdline-tools/
ls -l $folder/Android/cmdline-tools/tools
sudo chown $(whoami):$(whoami) -R $folder/Android

echo '
# ANDROID SDK
DEV_TOOLS="/home/$USER/DevTools"
JAVA_HOME="$DEV_TOOLS/JDK/"
ANDROID_HOME="$DEV_TOOLS/Android"
export JAVA_HOME
export ANDROID_HOME
PATH="$JAVA_HOME/bin:$ANDROID_HOME/cmdline-tools/tools/bin:$ANDROID_HOME/platform-tools:$PATH"' >> ~/.bashrc

sudo ln -s /usr/lib/jvm/java-8-openjdk-amd64 $DEV_TOOLS/JDK
source ~/.bashrc


sdkmanager --version
yes | sdkmanager --licenses
yes | sdkmanager "platform-tools" "platforms;android-29"
yes | sdkmanager "build-tools" "build-tools;29.0.3"

source ~/.bashrc
