#!/bin/bash

wget -qO- https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
sudo add-apt-repository -y "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"

I="$BASE_INSTALLER google-chrome-stable"
$(echo $I)
