#!/bin/bash
#gsettings list-recursively name # like org.gnome.desktop.wm.keybindings

name="${1}"
echo "$name"


input="./resources/$name/ubuntu/settings.txt"
i=1;
while IFS= read -r line
do
  i=$(($i+1))
  gsettings set $line
  echo $i:: gsettings set $line
done < "$input"